### ISSUE TITLE
Where and how to throw authtoken ngrok

### ISSUE THREAD

**Issue by AxolotlBro** [DimiDimit/Custom-LAN#34] opened 2024-04-20 19:42 UTC
I changed the config file and added a token between "" but it didn't change anything.  Then I restarted minecraft and tried to use tunnels again and minecraft just crashed (it looks like something that might help https://mclo.gs/QjMgKUt ) I have no idea what else can be done to make the mod see authtoken

Thank you for your help

**Comment by DimiDimit** [comment] 2024-04-26 19:05
It seems that outside of a dev environment, SnakeYAML is required… I thought I tested it, not sure how I missed that (or why this wasn't reported sooner—has no one used the ngrok tunnel until now, or did it suddenly stop working?).
v2.3.1 now includes it in the JAR. Tell me if it works so I can close this issue.

**Comment by muhammedesadcomert** [comment] 2024-04-27 16:22
> It seems that outside of a dev environment, SnakeYAML is required… I thought I tested it, not sure how I missed that (or why this wasn't reported sooner—has no one used the ngrok tunnel until now, or did it suddenly stop working?). v2.3.1 now includes it in the JAR. Tell me if it works so I can close this issue.

It works as intended, the issue can be closed.

**Comment by AxolotlBro** [comment] 2024-04-27 18:19
I checked the patch and now I don't crash minecraft, but when I ask to connect to the ip, I get a problem with the login and I restart minecraft (I have a pirate client), I checked on friends and they didn't work either 
Here is a log file that can help you figure it out https://mclo.gs/IEKkLiz 
![image](https://github.com/DimiDimit/Custom-LAN/assets/131779254/57c3d826-a4c9-4f30-8c00-33d556f8ee9c)
Here is the error itself on the screen
And I will add that we use this mod only to play with each other on the pirate, and the developer of world-host (a mod similar to yours) said that on the pirate you can connect via nrog and this is done through your mod

**Comment by DimiDimit** [comment] 2024-04-27 23:05
Did the host disable Online Mode when opening to LAN?

**Comment by AxolotlBro** [comment] 2024-04-28 12:05
it works and ngrok works well too. Thank you for your help

**Closed as completed** 2024-04-29 02:04 UTC
Labels: bug
